version: '3.7'

networks:
  traefik-public:
    external: true
#  interna:
#    external: false

services:
  mysql:
    container_name: b3_mysql
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - './mysql:/var/lib/mysql'
    networks:
      - traefik-public
    #      - interna
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: b3
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  phpmyadmin:
    container_name: b3_phpmyadmin
    image: phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - PMA_HOST=mysql
      - TZ=America/Maceio
      - UPLOAD_LIMIT=300M
    ports:
      - '9090:80'
    depends_on:
      - mysql
    networks:
      - traefik-public
    #     - interna
#    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      ## HTTP Routers
      # - traefik.http.routers.phpmyadmin-rtr.entrypoints=web
      - traefik.http.routers.phpmyadmin-rtr.entrypoints=websecure
      - traefik.http.routers.phpmyadmin-rtr.rule=Host(`phpmyadmin.ficker.tech`)
      - traefik.http.routers.phpmyadmin-rtr.tls=true
      - traefik.http.routers.phpmyadmin-rtr.tls.certresolver=letsencrypt
      ## HTTP Services
      - traefik.http.services.phpmyadmin-svc.loadbalancer.server.port=80
      # - traefik.http.routers.phpmyadmim-rtr.middlewares=basic-auth@file