import scrapy
import mysql.connector
from datetime import date
import time


class AdfnvSpider(scrapy.Spider):
    name = 'advfn'
    start_urls = [
        'https://br.advfn.com/bolsa-de-valores/bovespa/alliar-on-AALR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/abc-brasil-pn-ABCB4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/aeris-industria-e-comerc-on-AERI3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/aes-brasil-energia-on-AESB3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/afluente-on-AFLT3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/brasil-agro-on-AGRO3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/agrogalaxy-participacoes-on-AGXY3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/allied-tecnologia-on-ALLD3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/alpargatas-on-ALPA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/alpargatas-pn-ALPA4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/allpark-empreendimentos-on-ALPK3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/alupar-on-ALUP3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/alupar-pn-ALUP4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/lojas-marisa-on-AMAR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ambipar-participacoes-e-on-AMBP3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/americanas-on-AMER3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/anima-on-ANIM3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/alper-on-APER3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/arezzo-on-ARZZ3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/sendas-distribuidora-on-ASAI3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/atma-on-ATMP3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/atompar-on-ATOM3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/alphaville-on-AVLL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/azevedo-on-AZEV3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/azevedo-pn-AZEV4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/azul-pn-AZUL4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/bahema-educacao-on-BAHI3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/amazonia-on-BAZA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/banco-do-brasil-on-BBAS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/bradesco-on-BBDC3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/bradesco-pn-BBDC4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/bb-seguridade-on-BBSE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/bardella-pn-BDLL4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/minerva-on-BEEF3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/banestes-on-BEES3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/banestes-pn-BEES4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/banese-pn-BGIP4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/biomm-on-BIOM3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/blau-farmaceutica-on-BLAU3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/banco-mercantil-pn-BMEB4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/bmg-pn-BMGB4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/bic-monark-on-BMKS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/bemobi-tech-on-BMOB3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/banco-nordeste-on-BNBR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/boa-vista-on-BOAS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/coelce-pna-COCE5/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cogna-on-COGN3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/construtora-adolfo-l-on-CALI3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cambuci-on-CAMB3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/camil-alimentos-on-CAML3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/companhia-brasileira-de-on-CBAV3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ccr-on-CCRO3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/c-a-on-CEAB3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ceb-on-CEBR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ceb-pna-CEBR5/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ceb-pnb-CEBR6/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/coelba-on-CEEB3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/comgas-pna-CGAS5/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/grazziotin-pn-CGRA4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cielo-on-CIEL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/celesc-on-CLSC3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/celesc-pn-CLSC4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cemig-on-CMIG3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cemig-pn-CMIG4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/csn-mineracao-s-a-on-CMIN3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/dasa-on-DASA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/desktop-sigmanet-comun-on-DESK3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/dexxos-participacoes-s-a-on-DEXP3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/dexxos-participacoes-s-a-pn-DEXP4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/direcional-on-DIRR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/d1000-varejo-farma-parti-on-DMVF3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/dohler-pn-DOHL4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/dotz-on-DOTZ3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/dexco-on-DXCO3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/aco-altona-pn-EALT4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ecorodovias-on-ECOR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/engie-brasil-on-EGIE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/elektro-pn-EKTR4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/eletrobras-on-ELET3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/eletrobras-pnb-ELET6/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/eletromidia-on-ELMD3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/emae-pn-EMAE4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/embraer-on-EMBR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/enauta-on-ENAT3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/energias-br-on-ENBR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/eneva-on-ENEV3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/energisa-on-ENGI3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/energisa-pn-ENGI4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/enjoei-on-ENJU3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/embpar-participacoes-on-EPAR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/eqtl-para-on-EQPA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/equatorial-on-EQTL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/mpm-corporeos-on-ESPA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/eternit-on-ETER3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/eucatex-on-EUCA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/eucatex-pn-EUCA4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/even-on-EVEN3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/eztec-on-EZTC3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ferbasa-pn-FESA4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/fer-heringer-on-FHER3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/unifique-telecomunicacoes-on-FIQE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/fleury-on-FLRY3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/fras-le-on-FRAS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/pomifrutas-on-FRTA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ger-paranap-on-GEPA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ger-paranap-pn-GEPA4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/gafisa-on-GFSA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/gerdau-on-GGBR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/gerdau-pn-GGBR4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/gps-participacoes-e-empr-on-GGPS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/grupo-mateus-on-GMAT3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/gerdau-met-on-GOAU3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/gol-pn-GOLL4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/celgpar-on-GPAR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/grendene-on-GRND3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/general-shop-on-GSHP3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/guararapes-on-GUAR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/haga-on-HAGA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/haga-pn-HAGA4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/hapvida-on-HAPV3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/helbor-on-HBOR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/hidrovias-do-brasil-on-HBSA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/hercules-pn-HETA4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/hoteis-othon-pn-HOOT4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/hypera-on-HYPE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/infracommerce-caxaas-on-IFCM3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/igb-s-a-on-IGBR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/iguatemi-on-IGTI3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/inepar-on-INEP3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/inepar-pn-INEP4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/intelbras-s-a-on-INTB3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/irb-brasil-on-IRBR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/itausa-on-ITSA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/itausa-pn-ITSA4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/itau-unibanco-on-ITUB3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/itau-unibanco-pn-ITUB4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/jalles-machado-on-JALL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/jbs-on-JBSS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/joao-fortes-on-JFEN3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/jhsf-part-on-JHSF3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/jsl-on-JSLG3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/terra-santa-propriedades-on-LAND3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/lavvi-empreendimentos-im-on-LAVV3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/metal-leve-on-LEVE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/light-on-LIGT3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/lojas-quero-quero-on-LJQQ3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/le-lis-blanc-on-LLIS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/log-commercial-on-LOGG3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/log-in-on-LOGN3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/lopes-brasil-on-LPSB3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/lojas-renner-on-LREN3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/lupatech-on-LUPA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/livetech-da-bahia-indust-on-LVTC3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/hospital-mater-dei-s-a-on-MATD3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/mobly-on-MBLY3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/m-dias-branco-on-MDIA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/moura-dubeaux-on-MDNE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/imc-s-a-on-MEAL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/omega-energia-on-MEGA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/melnick-desenvolvimento-on-MELK3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/mangels-pn-MGEL4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/magazine-luiza-on-MGLU3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/mills-on-MILS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/multilaser-industrial-on-MLAS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/mundial-on-MNDL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/minupar-on-MNPR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/bco-modal-on-MODL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/movida-on-MOVI3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/marfrig-on-MRFG3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/mrv-on-MRVE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/mitre-realty-on-MTRE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/multiplan-on-MULT3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/iochp-maxion-on-MYPK3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/neoenergia-on-NEOE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/neogrid-participacoes-on-NGRD3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/getninjas-on-NINJ3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/nordon-met-on-NORD3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/natura-on-NTCO3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/odontoprev-on-ODPV3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ourofino-s-a-on-OFSA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/oi-on-OIBR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/oncoclinicas-brasil-serv-on-ONCO3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/oceanpact-servicos-marit-on-OPCT3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/orizon-valorizacao-de-re-on-ORVR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/osx-brasil-on-OSXB3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/pao-de-acucar-on-PCAR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/pdg-realt-on-PDGR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/padtec-on-PDTC3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/petrobras-on-PETR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/petrobras-pn-PETR4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/pet-center-comercio-e-pa-on-PETZ3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/profarma-on-PFRM3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/empreendimentos-pague-me-on-PGMN3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/pine-pn-PINE4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/plascar-part-on-PLAS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/plano-plano-desenvolvi-on-PLPL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/paranapanema-on-PMAM3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/dimed-on-PNVL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/marcopolo-on-POMO3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/marcopolo-pn-POMO4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/wilson-sons-holdings-bra-on-PORT3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/positivo-tec-on-POSI3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/petrorio-on-PRIO3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/priner-on-PRNR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/porto-seguro-on-PSSA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/portobello-on-PTBL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/pettenati-on-PTNT3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/pettenati-pn-PTNT4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/qualicorp-on-QUAL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/raia-drogasil-on-RADL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/rumo-s-a-on-RAIL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/raizen-s-a-pn-RAIZ4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/celulose-irani-on-RANI3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/randon-part-pn-RAPT4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/recrusul-on-RCSL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/recrusul-pn-RCSL4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/rni-on-RDNI3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/rede-dor-sao-luiz-on-RDOR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/petroreconcavo-on-RECV3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/rede-energia-on-REDE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/localiza-on-RENT3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/renova-on-RNEW3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/renova-pn-RNEW4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/inds-romi-on-ROMI3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/alfa-pna-RPAD5/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/alfa-pna-RPAD5/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/alfa-pna-RPAD5/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/3r-petroleum-oleo-e-gas-on-RRRP3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/rossi-resid-on-RSID3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/rio-sulense-pn-RSUL4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/santander-br-on-SANB3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/santander-br-pn-SANB4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/sanepar-on-SAPR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/sanepar-pn-SAPR4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/grupo-sbf-on-SBFG3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ser-educacional-on-SEER3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/sequoia-logistica-e-tran-on-SEQL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/springs-on-SGPS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/time-for-fun-on-SHOW3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/schulz-pn-SHUL4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/simpar-on-SIMH3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/slc-agricola-on-SLCE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/smartfit-on-SMFT3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/sao-martinho-on-SMTO3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/sansuy-pna-SNSY5/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/boa-safra-sementes-on-SOJA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/grupo-de-moda-soma-on-SOMA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/sinqia-on-SQIA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/santos-brasil-on-STBP3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/suzano-papel-on-SUZB3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/syn-prop-e-tech-s-a-on-SYNE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/taesa-on-TAEE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/taesa-pn-TAEE4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/forja-taurus-on-TASA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/forja-taurus-pn-TASA4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/tecnisa-on-TCSA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/technos-on-TECN3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/telebras-pn-TELB4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/track-field-pn-TFCO4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/tegma-on-TGMA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/totvs-on-TOTS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/triunfo-part-on-TPIS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/tc-on-TRAD3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/trisul-on-TRIS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/isa-cteep-on-TRPL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/isa-cteep-pn-TRPL4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/3tentos-on-nm-on-TTEN3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/tupy-on-TUPY3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/tex-renaux-pn-TXRX4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/unicasa-on-UCAS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ultrapar-on-UGPA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/unipar-on-UNIP3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/unipar-pnb-UNIP6/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/usiminas-on-USIM3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/usiminas-pna-USIM5/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/vale-on-VALE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/vamos-on-VAMO3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/vibra-energia-on-VBBR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/grupo-casas-bahia-on-VIIA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/vittia-on-VITT3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/vivara-on-VIVA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/viver-on-VIVR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/telef-brasil-on-VIVT3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/valid-on-VLID3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/vulcabras-on-VULC3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cm-hospitalar-on-VVEO3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/kepler-weber-on-KEPL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/klabin-on-KLBN3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/klabin-pn-KLBN4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/kora-saude-participacoes-on-KRSA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/weg-on-WEGE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/westwing-comercio-vareji-on-WEST3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/whirlpool-on-WHRL3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/wiz-s-a-on-WIZS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/wlm-pn-WLMM4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ambev-s-a-on-ABEV3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/aliansce-sonae-on-ALSO3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/armac-locacao-logistica-on-ARML3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/excelsior-pn-BAUH4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/bombril-pn-BOBR4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/banco-pan-pn-BPAN4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/brisanet-participacoes-on-BRIT3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/alfa-invest-on-BRIV3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/braskem-on-BRKM3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/braskem-pna-BRKM5/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/br-propert-on-BRPR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/banrisul-on-BRSR3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/banrisul-pnb-BRSR6/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/meliuz-s-a-on-CASH3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cpfl-energia-on-CPFE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/copel-on-CPLE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/copel-pnb-CPLE6/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/carrefour-on-CRFB3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cristal-pna-CRPG5/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cristal-pnb-CRPG6/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cosan-on-CSAN3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cruzeiro-do-sul-educacio-on-CSED3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/copasa-on-CSMG3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/sid-nacional-on-CSNA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cosern-on-CSRN3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cosern-pnb-CSRN6/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/karsten-pn-CTKA4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/coteminas-pn-CTNM4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/santanense-on-CTSA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/santanense-pn-CTSA4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cury-construtora-e-incor-on-CURY3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cvc-brasil-on-CVCB3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/caixa-seguridade-partici-on-CXSE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cyrela-realt-on-CYRE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/energisa-mt-on-ENMT3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/gerdau-met-pn-GOAU4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/hbr-realty-empreendiment-on-HBRE3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/locaweb-on-LWSA3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/metisa-pn-MTSA4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/wetzel-pn-MWET4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/oi-pn-OIBR4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ihpardini-on-PARD3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/randon-part-on-RAPT3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/sabesp-on-SBSP3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/saraiva-livr-pn-SLED4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/teka-pn-TEKA4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/tenda-on-TEND3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/tim-on-TIMS3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/whirlpool-pn-WHRL4/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/estacio-part-on-YDUQ3/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/archer-daniels-midland-A1DM34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/dell-technologies-D1EL34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/d-r-horton-D1HI34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/docusign-D1OC34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/dominos-pizza-D2PZ34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/german-ak-dnr-DBAG34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/deere-DEEC34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/delta-drn-DEAI34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/diamondback-energy-F1AN34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/f5-F1FI34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/fmc-F1MC34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/fastly-F1SL34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/fortinet-F1TN34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/hasbro-H1AS34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/hca-healthcare-H1CA34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/hdfc-bank-H1DB34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/harley-davidson-H1OG34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/hewlett-packard-enterprise-H1PE34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/her-block-H1RB34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/hsbc-H1SB34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/humana-H1UM34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/horizon-therapeutics-H1ZN34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/healthcare-realty-H2TA34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/idexx-laboratories-I1DX34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/illumina-I1LM34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/johnson-controls-J1CI34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/nordstrom-J1WN34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/jd-com-JDCO34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/johnson-johnson-JNJB34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/lloyds-banking-L1YG34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/jpmorgan-chase-JPMC34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/laboratory-corp-of-america-L1CA34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/leidos-L1DO34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/linde-L1IN34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/lumen-technologies-L1MN34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/live-nation-entertainment-L1YV34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/liberty-broadband-LBRD34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/neurocrine-biosciences-N1BI34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/newmont-N1EM34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/servicenow-N1OW34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/novo-nordisk-N1VO34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/novartis-N1VS34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/nxp-semiconductors-nv-N1XP34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/cloudflare-N2ET34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/netease-NETE34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/okta-O1KT34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/omnicom-O1MC34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/on-semiconductor-O2NS34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/oracle-ORCL34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/occidental-petroleum-OXYP34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/pdd-P1DD34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/the-progressive-P1GR34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/amcor-A1CR34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/analog-devices-A1DI34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/datadog-D1DG34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/dexcom-D1EX34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/dow-D1OW34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/devon-energy-D1VN34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/fastenal-FASL34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/freeport-mcmoran-FCXO34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ford-motor-FDMO34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/general-electric-GEOO34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/gold-fields-G1FI34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/galapagos-nv-G1LP34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/gsk-G1SK34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/g2d-investments-G2DI33/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/vaneck-durable-high-divi-GDXB39/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/qorvo-Q1RV34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/quantumscape-Q2SC34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/qualcomm-QCOM34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/royal-caribbean-R1CL34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/relx-R1EL34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/realty-incomdrn-R1IN34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/roku-R1KU34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/roblox-R2BL34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/redfin-R2DF34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ringcentral-R2NG34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/sibanye-stillwater-S1BS34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/tal-education-T1AL34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/atlassian-T1AM34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/bio-techne-T1CH34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/technipfmc-T1EC34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/t-mobile-us-T1MU34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/american-tower-T1OW34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/t-rowe-price-T1RO34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/under-armour-U1AI34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/united-airlines-U1AL34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/uber-technologies-U1BE34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/ulta-beauty-U1LT34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/united-rentals-U1RI34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/upstart-U2PS34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/unity-software-U2ST34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/unilever-ULEV34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/unitedhealth-UNHH34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/united-parcel-service-UPSS34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/u-s-bancorp-USBC34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/united-states-steel-USSX34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/vornado-realty-V1NO34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/vodafone-V1OD34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/vmware-V2MW34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/verizon-communications-VERZ34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/visa-VISA34/cotacao',
        'https://br.advfn.com/bolsa-de-valores/bovespa/zoom-video-communications-Z1OM34/cotacao'
                  ]
    counter = 0

    connection = mysql.connector.connect(
        host='127.0.0.1',
        port=3306,
        user='root',
        password='admin',
        database='b3'
    )
    cursor = connection.cursor()

    def parse(self, response):
        data = date.today()
        horario = time.strftime("%H:%M:%S")
        hora = int(horario[0:2])
        minuto = int(horario[3:5])

        empresa = response.css('#quote_top :nth-child(1)::text')[10].get()
        abertura = response.css('#quote_top :nth-child(1)::text')[41].get().replace(",", ".")
        maximo = response.css('#quote_top :nth-child(1)::text')[43].get().replace(",", ".")
        minimo = response.css('#quote_top :nth-child(1)::text')[42].get().replace(",", ".")
        variacao = response.css('#quote_top :nth-child(1)::text')[27].get().replace(",", ".")

        if (hora == 18 and minuto >= 20) or hora > 18 or hora < 8:
            fechamento = response.css('#quote_top :nth-child(1)::text')[44].get().replace(",", ".")
            ff_anterior = response.css('#quote_top :nth-child(1)::text')[45].get().replace(",", ".")
            volume_financeiro = response.css('#quote_top :nth-child(1)::text')[60].get().replace(".", "")
            if volume_financeiro[0] == 'R':
                volume_real = volume_financeiro[3:]
            else:
                volume_real = volume_financeiro[1:]
            volume_acoes = response.css('#quote_top :nth-child(1)::text')[58].get().replace(".", "")
            volume_negocios = response.css('#quote_top :nth-child(1)::text')[57].get().replace(".", "")
        else:
            fechamento = response.css('#quote_top :nth-child(1)::text')[29].get().replace(",", ".")
            ff_anterior = response.css('#quote_top :nth-child(1)::text')[44].get().replace(",", ".")
            volume_financeiro = response.css('#quote_top :nth-child(1)::text')[59].get().replace(".", "")
            if volume_financeiro[0] == 'R':
                volume_real = volume_financeiro[3:]
            else:
                volume_real = volume_financeiro[1:]
            volume_acoes = response.css('#quote_top :nth-child(1)::text')[57].get().replace(".", "")
            volume_negocios = response.css('#quote_top :nth-child(1)::text')[56].get().replace(".", "")

        if maximo[0].isnumeric():
            maximo = float(maximo)
            ff_anterior = float(ff_anterior)
            percentual = ((maximo / ff_anterior) - 1) * 100
        else:
            insert = f"INSERT INTO `tb_empresa` (`EMPRESA`) VALUES ('{empresa}')"
            self.cursor.execute(insert)
            maximo, minimo, abertura, fechamento, ff_anterior, volume_real, variacao, percentual, volume_acoes, volume_negocios = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

        if self.counter == 0:
            delete = f"DELETE FROM `tb_cotacao` WHERE DATA = '{data}';"
            self.cursor.execute(delete)

        insert = f"INSERT INTO `tb_cotacao` (`EMPRESA`, `ABERTURA`, `MAXIMO`, `MINIMO`, `FECHAMENTO`, " \
                  f"`FECHAMENTO_ANTERIOR`, `DATA`, `VOLUME_FINANCEIRO`, `VOLUME_ACOES`, `VOLUME_NEGOCIOS`, `VARIACAO`, `PERCENTUAL`)" \
                  f" VALUES ('{empresa}','{abertura}','{maximo}','{minimo}','{fechamento}'," \
                  f"'{ff_anterior}','{data}','{volume_real}','{volume_acoes}','{volume_negocios}','{variacao}', '{percentual}')"

        self.cursor.execute(insert)
        self.connection.commit()
        self.counter += 1

        if self.counter >= 449:
            self.cursor.close()
            self.connection.close()