import scrapy
import mysql.connector
from datetime import date


class ItauSpider(scrapy.Spider):
    name = "itau"
    start_urls = [
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=AALR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=AGXY3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ABCB4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ALLD3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=AESB3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=AGRO3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=AFLT3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=AERI3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ALPA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ALPA4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ALPK3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=AMBP3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ALUP4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=AMAR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ALUP3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ANIM3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=APER3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=AMER3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ARZZ3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ASAI3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ATOM3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ATMP3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=AZEV4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=AZEV3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BAHI3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=AVLL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BBAS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BBDC3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=AZUL4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BBDC4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BBSE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BDLL4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BEES3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BEES4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BAZA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BGIP4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BEEF3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BLAU3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BIOM3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BMGB4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BMEB4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BMKS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BNBR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=COCE5&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BMOB3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CALI3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CAMB3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CAML3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BOAS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CBAV3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CCRO3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CEBR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CEAB3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CEBR5&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=COGN3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CEBR6&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CEEB3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CGRA4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CIEL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CLSC3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CLSC4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CGAS5&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CMIG4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CMIN3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=DESK3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CMIG3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=DEXP4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=DEXP3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=DMVF3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=DIRR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=DOHL4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=DOTZ3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=DASA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=EALT4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=DXCO3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ECOR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=EGIE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=EKTR4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ELET3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ELET6&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=EMAE4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=EMBR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ELMD3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ENAT3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ENBR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ENGI3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ENGI4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ENEV3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ENJU3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=EPAR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=EQPA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ESPA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=EQTL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ETER3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=EUCA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=EUCA4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=EVEN3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=EZTC3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=FESA4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=FIQE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=FHER3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=GEPA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=FRAS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=FRTA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=FLRY3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=GEPA4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=GFSA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=GGBR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=GGBR4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=GGPS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=GMAT3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=GOAU3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=GSHP3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=GOLL4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=GRND3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=GPAR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=GUAR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=HAGA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=HAGA4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=HAPV3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=HBOR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=HBSA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=HETA4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=IFCM3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=IGBR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=IGTI3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=INEP3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=HYPE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=INTB3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=INEP4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=HOOT4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=IRBR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ITSA4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ITUB3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=JALL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=JBSS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ITUB4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=JFEN3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ITSA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=LAND3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=JSLG3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=JHSF3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=LAVV3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=LEVE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=LIGT3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=LJQQ3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=LOGG3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=LOGN3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=LLIS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=LREN3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=LPSB3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=LVTC3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=LUPA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MATD3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MBLY3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MDIA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MDNE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MEAL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MEGA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MELK3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MGEL4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MGLU3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MILS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MLAS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MNDL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MNPR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MODL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MOVI3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MRFG3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MTRE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MRVE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MULT3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MYPK3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=NEOE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=NGRD3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=NINJ3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=NORD3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=NTCO3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ODPV3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=OFSA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ONCO3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=OIBR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=OPCT3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ORVR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=OSXB3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PCAR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PDGR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PDTC3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PETZ3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PETR4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PETR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PLAS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PFRM3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PGMN3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PINE4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PLPL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PNVL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PMAM3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PORT3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=POMO4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=POMO3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PRIO3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=POSI3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PRNR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PSSA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PTBL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PTNT3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PTNT4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=QUAL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RAIZ4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RAIL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RADL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RAPT4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RANI3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=REDE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RCSL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RCSL4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RDNI3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RECV3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RDOR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RNEW3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RNEW4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RPAD5&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RENT3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RPAD5&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RRRP3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RPAD5&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ROMI3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RSUL4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SANB3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SANB4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SAPR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SBFG3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SAPR4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SEQL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RSID3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SGPS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SHOW3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SHUL4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SEER3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SIMH3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SLCE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SMFT3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SOJA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SNSY5&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SOMA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SQIA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=STBP3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SMTO3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SUZB3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SYNE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TAEE4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TAEE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TASA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TASA4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TECN3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TCSA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TFCO4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TELB4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TGMA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TPIS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TOTS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TRAD3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TRIS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TRPL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TTEN3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TRPL4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TUPY3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TXRX4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=UCAS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=UGPA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=UNIP3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=UNIP6&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=USIM3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=VAMO3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=USIM5&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=VALE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=VBBR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=VIIA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=VITT3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=VIVT3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=VIVR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=VVEO3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=VULC3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=VIVA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=KEPL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=VLID3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=KLBN3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=KRSA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=WEST3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=KLBN4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=WIZS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=WHRL3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=WLMM4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ABEV3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BAUH4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ARML3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=WEGE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BOBR4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BRIT3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BRIV3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ALSO3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BPAN4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BRKM3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BRKM5&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BRSR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BRPR3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=BRSR6&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CASH3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CPLE6&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CRFB3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CPFE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CPLE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CRPG6&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CSED3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CSAN3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CRPG5&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CSMG3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CSNA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CSRN3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CTKA4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CTNM4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CTSA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CURY3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CSRN6&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CTSA4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CXSE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CYRE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ENMT3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=HBRE3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=GOAU4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=LWSA3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MTSA4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=MWET4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=OIBR4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=PARD3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=CVCB3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=RAPT3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SBSP3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TEKA4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TIMS3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=A1DM34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=TEND3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=WHRL4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=YDUQ3&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=D1EL34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=D1OC34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=DBAG34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=D2PZ34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=D1HI34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=DEEC34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=SLED4&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=F1AN34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=F1FI34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=F1MC34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=DEAI34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=H1AS34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=F1SL34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=F1TN34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=H1CA34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=H1DB34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=H1OG34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=H1PE34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=H1RB34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=H1UM34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=H1SB34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=H1ZN34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=JDCO34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=I1DX34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=I1LM34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=J1WN34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=JNJB34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=L1YG34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=H2TA34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=L1DO34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=L1MN34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=JPMC34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=J1CI34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=L1CA34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=L1IN34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=L1YV34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=N1OW34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=N1BI34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=N1EM34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=LBRD34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=N1VS34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=N1XP34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=N1VO34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=O1KT34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=O1MC34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=NETE34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=N2ET34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ORCL34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=OXYP34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=O2NS34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=A1CR34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=P1DD34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=A1DI34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=D1OW34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=P1GR34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=D1EX34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=FASL34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=D1VN34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=D1DG34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=FCXO34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=FDMO34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=GEOO34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=G1LP34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=G1SK34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=G2DI33&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=GDXB39&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=G1FI34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=Q2SC34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=Q1RV34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=R1EL34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=R1CL34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=QCOM34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=R2DF34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=R1KU34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=R2BL34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=R2NG34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=T1AM34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=R1IN34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=S1BS34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=T1AL34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=T1CH34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=T1EC34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=T1OW34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=T1RO34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=U1AL34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=U1LT34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=T1MU34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=U1AI34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=U1RI34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=U2ST34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=U2PS34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=ULEV34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=UNHH34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=U1BE34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=USSX34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=UPSS34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=V1NO34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=USBC34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=V2MW34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=VERZ34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=V1OD34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=Z1OM34&type=stock',
        'https://www.itaucorretora.com.br/Finder/Finder/?stock=VISA34&type=stock'
    ]
    counter = 0

    connection = mysql.connector.connect(
        host='127.0.0.1',
        port=3306,
        user='root',
        password='admin',
        database='b3'
    )
    cursor = connection.cursor()

    def num_extract(self, value):
        num = ''
        for i in value:
            if i.isnumeric():
                num += i
        return num

    def volume_formatter(self, value):
        if value[-1] == 'K':
            volume = float(value[:-1]) * 1000
        elif value[-1] == 'M':
            volume = float(value[:-1]) * 1000000
        elif value[-1] == 'B':
            volume = float(value[:-1]) * 1000000000
        else:
            volume = float(value)
        return volume

    def parse(self, response):
        data = date.today()

        abertura = response.css('.valor-destaque::text')[0].get().replace(",", ".")
        empresa = response.css('strong::text')[0].get()

        if abertura == '0.00':
            maximo, minimo, abertura, fechamento, ff_anterior, volume_real, variacao, percentual, volume_acoes, volume_negocios, volume_financeiro = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        else:
            ff_anterior = response.css('.valor-destaque::text')[1].get().replace(",", ".")
            volume_negocios = self.num_extract(response.css('.valores::text')[1].get())
            fechamento = self.num_extract(response.css('strong::text')[1].get())
            variacao = response.css('span::text')[3].get().replace(",", ".")[14:-1]

            if len(response.css('strong::text').getall()) > 8:
                maximo = response.css('strong::text')[4].get().replace(",", ".")
                minimo = response.css('strong::text')[5].get().replace(",", ".")
            else:
                maximo = response.css('strong::text')[2].get().replace(",", ".")
                minimo = response.css('strong::text')[3].get().replace(",", ".")

            volume_financeiro = self.volume_formatter(response.css('.valor-destaque::text')[2].get().replace(",", "."))

            volume_acoes = int(float(volume_financeiro) / ((float(maximo) + float(minimo)) / 2))
            percentual = ((float(maximo) / float(ff_anterior)) - 1) * 100

        if self.counter == 0:
            delete = f"DELETE FROM `tb_cotacao` WHERE DATA = '{data}';"
            self.cursor.execute(delete)

        # insert_empresas = f"INSERT INTO `tb_empresa` (`EMPRESA`) VALUES ('{empresa}')"

        insert = f"INSERT INTO `tb_cotacao` (`EMPRESA`, `ABERTURA`, `MAXIMO`, `MINIMO`, `FECHAMENTO`, " \
                 f"`FECHAMENTO_ANTERIOR`, `DATA`, `VOLUME_FINANCEIRO`, `VOLUME_ACOES`, `VOLUME_NEGOCIOS`, `VARIACAO`, `PERCENTUAL`)" \
                 f" VALUES ('{empresa}','{abertura}','{maximo}','{minimo}','{fechamento}'," \
                 f"'{ff_anterior}','{data}','{volume_financeiro}','{volume_acoes}','{volume_negocios}','{variacao}', '{percentual}')"

        # self.cursor.execute(insert_empresas)
        self.cursor.execute(insert)
        self.connection.commit()
        self.counter += 1

        if self.counter >= 448:
            self.cursor.close()
            self.connection.close()
